/*
 * ESPACK __ESPAK_VERSION__ self-extracting ExternalObject bundle (generated by espack-build.mjs - do not edit).
 * Bundle: __BUNDLE_NAME__
 * Payloads (n): __PAYLOAD_SUMMARY__
 * Accelerator (1, shared across all espack bundles): __ACCEL_SUMMARY__
 * Cache dirs: payloads %LOCALAPPDATA%/<bundle name>, accelerator %LOCALAPPDATA%/espack (or __ACCEL_DIR__)
 * Runtime decode chunk: __CHUNK_SIZE__ base64 chars per pass (JSX lane; measured: linear atob, no engine wedge)
 * Accel-less bundles discover the shared accelerator at %LOCALAPPDATA%/espack/ESB64Native_v1.dll
 * (materialized by any accel-carrying bundle) for native payload decode; absent -> JSX lane.
 */
var ESPACK = (function () {
  var PAYLOADS = __PAYLOADS__;
  var CHUNK = __CHUNK_SIZE__;
  var BUNDLE_NAME = "__BUNDLE_NAME__";
  var CACHE_DIR_OVERRIDE = "__CACHE_DIR__";
  var ACCEL_NAME = "__ACCEL_NAME__";
  var ACCEL_VERSION = "__ACCEL_VERSION__";
  var ACCEL_LEN = __ACCEL_LEN__;
  var ACCEL_B64 = "__ACCEL_B64__";
  var ACCEL_DIR_OVERRIDE = "__ACCEL_DIR__";
  var ESPAK_VERSION = "__ESPAK_VERSION__";

  /* Shared-accel discovery (accel-less bundles): the canonical shared
     accelerator that every accel-carrying bundle materializes once per
     system at %LOCALAPPDATA%/espack/. An accel-less bundle reuses it for
     native payload decode instead of the JSX lane. */
  var SHARED_ACCEL_NAME = "ESB64Native";
  var SHARED_ACCEL_VERSION = "2";

  var state = { mode: "es3", lib: null, lastError: "", extracted: {}, accelReady: false, accelLib: null, accelExtractMs: -1, nativeExtractMs: -1, payloadExtractMs: -1, loadMs: -1 };
  /* Public config must track the live shared registry. An idempotent loader
     survives later bundle evals, so a one-time payloadSummary() snapshot would
     otherwise lie about newly registered payload versions/kinds/counts. */
  var publicConfig = null;

  function refreshPublicPayloads() {
    if (publicConfig) publicConfig.payloads = payloadSummary();
  }

__ESB64_RUNTIME__

  /* Single-base64 policy (Option C): prefer the canonical shared codec the
     host bundle installs ($.global.ESB64.atob), falling back to this bundle's
     inlined lane (the runtime template slot) only when no shared codec is
     present. The inlined lane stays for standalone/accel-less bundles; hosts
     that inject esb64 (esb64-atob.jsx) provide the canonical impl so the two
     never both run. */
  function b64Atob(s) {
    try {
      var g = null;
      if (typeof $ !== "undefined" && $.global) g = $.global;
      if (g && g.ESB64 && typeof g.ESB64.atob === "function") return g.ESB64.atob(s);
    } catch (ignoreShared) {}
    return __espakB64.atob(s);
  }

  /* Idempotent loader (Option B): expose a runtime registration API so a
     multi-bundle file installs ONE loader runtime; later bundles register
     their payloads instead of shipping a second loader. Mirror of
     espack-merge.mjs:96-109: same name+version+bytes dedupes, same name with
     a higher integer version upgrades, conflicts throw. */
  function registerPayload(p) {
    if (!p || typeof p.name !== "string") return;
    var i, prev;
    for (i = 0; i < PAYLOADS.length; i++) {
      if (PAYLOADS[i].name === p.name) { prev = PAYLOADS[i]; break; }
    }
    if (!prev) { PAYLOADS[PAYLOADS.length] = p; refreshPublicPayloads(); return; }
    if (prev.version === p.version) {
      if (prev.b64 !== p.b64 || prev.len !== p.len) {
        throw new Error("ESPAK: payload conflict for " + p.name + " v" + p.version);
      }
      return;
    }
    var pv = parseInt(String(prev.version), 10);
    var nv = parseInt(String(p.version), 10);
    if (isNaN(pv) || isNaN(nv) || nv <= pv) return;
    PAYLOADS[i] = p;
    refreshPublicPayloads();
  }

  /* Register THIS bundle's payloads into an existing loader runtime (the boot
     IIFE calls this when a prior bundle already installed the loader).
     Front-registration preserves the espack facade rule: the LAST-registered
     bundle's payload 0 is what load(0) resolves to, exactly as if this bundle
     had installed its own loader (existing "payload bundle is the active
     facade" convention). Returns true when merged; false tells the boot to
     replace the runtime instead (this bundle carries a DIFFERENT accel — a
     version upgrade, not a same-load merge). */
  function registerInto(existing) {
    /* A pre-fix shared runtime cannot resolve the accelerator by name once it
       owns payloads. Do not merge into it: replace that runtime once so
       long-lived Illustrator engines acquire the corrected resolver. */
    if (!existing || existing.supportsAccelTargetName !== true) return false;
    if (accelUpgrades(existing)) return false;
    var list = [];
    var k;
    /* stamp each registered payload with its ORIGIN bundle cache dir so a
       foreign payload still extracts to its own dir under a shared runtime */
    for (k = 0; k < PAYLOADS.length; k++) {
      list[list.length] = { name: PAYLOADS[k].name, version: PAYLOADS[k].version, len: PAYLOADS[k].len, b64: PAYLOADS[k].b64, fileName: PAYLOADS[k].fileName, kind: PAYLOADS[k].kind, dir: cacheDir() };
    }
    try { existing.registerPayloadsFront(list); } catch (regErr) { return false; }
    return true;
  }

  /* Merge only when the payload capability set is compatible: an accel-less
     bundle reuses an existing accel; identical accels merge; a bundle that
     carries a DIFFERENT embedded accel is a new version and must REPLACE the
     old runtime (its extraction + GC semantics take over). */
  function accelUpgrades(existing) {
    var exAccel = null;
    try { exAccel = existing.config ? existing.config.accel : null; } catch (ignoreCfg) {}
    if (!hasAccel()) return false;          /* accel-less: always mergeable */
    if (!exAccel) return true;              /* we carry an accel, old had none -> upgrade */
    return exAccel.name !== ACCEL_NAME || exAccel.version !== ACCEL_VERSION || exAccel.len !== ACCEL_LEN;
  }

  /* Front-register this bundle so its payload 0 becomes the shared runtime's
     index 0. Rebuild through registerPayload() so duplicate names obey the
     same version/conflict rules as every other registration path. */
  function registerPayloadsFront(list) {
    if (!list || !list.length) return;
    var old = [];
    var i;
    for (i = 0; i < PAYLOADS.length; i++) old[i] = PAYLOADS[i];
    PAYLOADS.length = 0;
    for (i = 0; i < list.length; i++) registerPayload(list[i]);
    for (i = 0; i < old.length; i++) registerPayload(old[i]);
    refreshPublicPayloads();
  }

  function pathJoin(a, b) {
    var s = String(a);
    if (s.charAt(s.length - 1) !== "/") s += "/";
    return s + String(b);
  }

  function defaultCacheDir(name) {
    var la = null;
    try { la = $.getenv("LOCALAPPDATA"); } catch (e1) {}
    if (la) return pathJoin(String(la).replace(/\\/g, "/"), name);
    try { return pathJoin(Folder.temp.fsName.replace(/\\/g, "/"), "espack/" + name); } catch (e2) {}
    return pathJoin("C:/Users/Public/espack", name);
  }

  function cacheDir() {
    if (CACHE_DIR_OVERRIDE) return String(CACHE_DIR_OVERRIDE).replace(/\\/g, "/");
    return defaultCacheDir(BUNDLE_NAME);
  }

  function accelDir() {
    if (ACCEL_DIR_OVERRIDE) return String(ACCEL_DIR_OVERRIDE).replace(/\\/g, "/");
    return defaultCacheDir("espack");
  }

  function payloadPath(i) { return pathJoin(payloadCacheDir(i), PAYLOADS[i].fileName); }
  /* A registered foreign payload keeps its originating bundle's cache dir
     (set by registerInto) so extraction lands in the right place even though
     one loader runtime now serves every bundle in the file. */
  function payloadCacheDir(i) {
    return PAYLOADS[i].dir ? String(PAYLOADS[i].dir) : cacheDir();
  }
  function accelFileName() { return ACCEL_NAME + "_v" + ACCEL_VERSION + ".dll"; }
  function sharedAccelPath() { return pathJoin(accelDir(), SHARED_ACCEL_NAME + "_v" + SHARED_ACCEL_VERSION + ".dll"); }
  function accelPath() {
    if (hasAccel()) return pathJoin(accelDir(), accelFileName());
    return sharedAccelPath();
  }
  function hasAccel() { return ACCEL_LEN > 0; }

  function ensureDir(fsPath) {
    var parts = String(fsPath).split("/");
    if (parts.length < 2) return new Folder(fsPath).exists;
    var cur = parts[0] + "/" + parts[1];
    var i, f;
    for (i = 2; i < parts.length; i++) {
      cur += "/" + parts[i];
      f = new Folder(cur);
      if (!f.exists && !f.create()) return false;
    }
    return true;
  }

  function isExtracted(i) {
    try {
      var f = new File(payloadPath(i));
      if (!f.exists) return false;
      return f.length === PAYLOADS[i].len;
    } catch (e) { return false; }
  }

  function isAccelExtracted() {
    try {
      var f = new File(accelPath());
      if (!f.exists) return false;
      return f.length === ACCEL_LEN;
    } catch (e) { return false; }
  }

  function gcOldVersions(dir, name, currentFile) {
    try {
      var folder = new Folder(dir);
      var matches = folder.getFiles(name + "_v*");
      var i;
      for (i = 0; i < matches.length; i++) {
        if (String(matches[i].name) !== currentFile) {
          try { matches[i].remove(); } catch (ignore) {}
        }
      }
    } catch (ignore) {}
  }

  function gcPayloadOld(i) { gcOldVersions(payloadCacheDir(i), PAYLOADS[i].name, PAYLOADS[i].fileName); }
  function gcAccelOld() { gcOldVersions(accelDir(), ACCEL_NAME, accelFileName()); }

  /* JSX lane: chunked atob decode -> per-chunk BINARY writes -> length verify. */
  function jsxWriteExtracted(b64, len, path, gcDir, gcName, gcCurrent) {
    var out = [];
    var n = b64.length;
    var i = 0;
    try {
      while (i < n) {
        var end = i + CHUNK;
        if (end > n) end = n;
        out.push(b64Atob(b64.substring(i, end)));
        i = end;
      }
    } catch (decodeError) {
      state.lastError = "ESPAK: base64 decode failed: " + String(decodeError) + "; staying in ES3 mode";
      return false;
    }
    var f = new File(path);
    f.encoding = "BINARY";
    var wroteAll = true;
    try {
      if (!f.open("w")) {
        state.lastError = "ESPAK: cannot open \"" + path + "\" for writing; staying in ES3 mode";
        return false;
      }
      var j;
      for (j = 0; j < out.length; j++) {
        if (!f.write(out[j])) wroteAll = false;
      }
      f.close();
    } catch (e) {
      try { f.close(); } catch (e2) {}
      state.lastError = "ESPAK: extraction write failed: " + String(e);
      return false;
    }
    if (!wroteAll || f.length !== len) {
      state.lastError = "ESPAK: extracted file is " + f.length + " bytes, expected " + len + "; staying in ES3 mode";
      try { f.remove(); } catch (e3) {}
      return false;
    }
    gcOldVersions(gcDir, gcName, gcCurrent);
    return true;
  }

  function extractAccel() {
    state.accelExtractMs = -1;
    if (!hasAccel()) return false;
    if (isAccelExtracted()) return true;
    if (!ensureDir(accelDir())) {
      state.lastError = "ESPAK: cannot create accelerator dir \"" + accelDir() + "\"; payloads will use the JSX lane";
      return false;
    }
    var t0 = 0;
    try { $.hiresTimer; t0 = $.hiresTimer; } catch (e0) {}
    var ok = jsxWriteExtracted(ACCEL_B64, ACCEL_LEN, accelPath(), accelDir(), ACCEL_NAME, accelFileName());
    if (ok) {
      try { state.accelExtractMs = $.hiresTimer - t0; } catch (e1) {}
    }
    return ok;
  }

  function loadAccelLib() {
    if (hasAccel()) {
      if (extractAccel()) {
        var fsPath = null;
        try { fsPath = new File(accelPath()).fsName; } catch (e2) { fsPath = accelPath(); }
        var cached = cachedLib(accelPath());
        if (cached) {
          state.accelLib = cached;
          state.accelReady = true;
          return true;
        }
        try {
          var lib = new ExternalObject("lib:" + fsPath);
          cacheLib(accelPath(), lib);
          state.accelLib = lib;
          state.accelReady = true;
          return true;
        } catch (e3) {
          state.lastError = "ESPAK: accelerator load failed: " + String(e3) + "; payloads will use the JSX lane";
          return false;
        }
      }
      /* embedded accel extraction failed (e.g. read-only cache): fall back to
         the shared accelerator already on the system, if any */
      return loadSharedAccel();
    }
    /* accel-less bundle: discover the shared accelerator another bundle
       already materialized on this system and reuse it for native decode */
    return loadSharedAccel();
  }

  /* Accel-less bundle: reuse the shared accelerator at the canonical path
     (%LOCALAPPDATA%/espack/ESB64Native_v1.dll). Fail-open: a missing file, a
     load failure, or a non-accelerator DLL at that path all keep the JSX lane
     with the reason surfaced. */
  function loadSharedAccel() {
    var p = sharedAccelPath();
    try {
      var f = new File(p);
      if (!f.exists || f.length === 0) {
        state.lastError = "ESPAK: shared accelerator not found at " + p + "; payloads will use the JSX lane";
        return false;
      }
    } catch (e) {
      state.lastError = "ESPAK: shared accelerator discovery failed: " + String(e) + "; payloads will use the JSX lane";
      return false;
    }
    var fsPath = null;
    try { fsPath = new File(p).fsName; } catch (e2) { fsPath = p; }
    var cached = cachedLib(p);
    if (cached) {
      state.accelLib = cached;
      state.accelReady = true;
      return true;
    }
    try {
      var lib = new ExternalObject("lib:" + fsPath);
      if (typeof lib.b64decodeToFile !== "function") {
        state.lastError = "ESPAK: shared accelerator at " + p + " is not the ESB64Native accelerator; payloads will use the JSX lane";
        return false;
      }
      cacheLib(p, lib);
      state.accelLib = lib;
      state.accelReady = true;
      return true;
    } catch (e3) {
      state.lastError = "ESPAK: shared accelerator load failed: " + String(e3) + "; payloads will use the JSX lane";
      return false;
    }
  }

  function libCache() {
    var g = null;
    try { if (typeof $ !== "undefined" && $.global) { g = $.global; } } catch (e1) {}
    if (!g) return null;
    if (!g.__ESPAK_LIBS__) g.__ESPAK_LIBS__ = {};
    return g.__ESPAK_LIBS__;
  }

  function cachedLib(path) {
    var c = libCache();
    return c ? (c[path] || null) : null;
  }

  function cacheLib(path, lib) {
    var c = libCache();
    if (c) c[path] = lib;
  }

  /* Native lane: the shared accelerator decodes the payload straight to
     disk (b64decodeToFile - NUL-safe, no string channel). Any error code,
     non-numeric result, or length mismatch falls back to the JSX lane. */
  function nativeExtractPayload(i) {
    state.nativeExtractMs = -1;
    if (!state.accelReady || !state.accelLib) return false;
    if (!ensureDir(payloadCacheDir(i))) {
      state.lastError = "ESPAK: cannot create cache dir \"" + payloadCacheDir(i) + "\"; staying in ES3 mode";
      return false;
    }
    var t0 = 0;
    try { $.hiresTimer; t0 = $.hiresTimer; } catch (e0) {}
    var n = null;
    try { n = state.accelLib.b64decodeToFile(PAYLOADS[i].b64, payloadPath(i)); } catch (e) {
      state.lastError = "ESPAK: native extraction failed (" + String(e) + "); falling back to the JSX lane";
      return false;
    }
    if (typeof n !== "number" || n !== PAYLOADS[i].len) {
      state.lastError = "ESPAK: native extraction returned " + n + " bytes, expected " + PAYLOADS[i].len + "; falling back to the JSX lane";
      try { new File(payloadPath(i)).remove(); } catch (e1) {}
      return false;
    }
    gcPayloadOld(i);
    try { state.nativeExtractMs = $.hiresTimer - t0; } catch (e2) {}
    return true;
  }

  function extractPayload(i) {
    state.payloadExtractMs = -1;
    var t0 = 0;
    try { $.hiresTimer; t0 = $.hiresTimer; } catch (e0) {}
    var r = nativeExtractPayload(i);
    if (!r) {
      /* the native failure reason stays in state.lastError (surfaced even
         when the JSX-lane fallback succeeds); clear it for the JSX attempt
         only when it was a hard cache-dir failure we are about to retry. */
      var nativeNote = state.lastError;
      if (!ensureDir(payloadCacheDir(i))) {
        state.lastError = "ESPAK: cannot create cache dir \"" + payloadCacheDir(i) + "\"; staying in ES3 mode";
        return { ok: false, error: state.lastError };
      }
      var wrote = jsxWriteExtracted(PAYLOADS[i].b64, PAYLOADS[i].len, payloadPath(i), payloadCacheDir(i), PAYLOADS[i].name, PAYLOADS[i].fileName);
      if (!wrote) return { ok: false, error: state.lastError };
      if (nativeNote) state.lastError = nativeNote + " (payload extracted via the JSX lane instead)";
    }
    try { state.payloadExtractMs = $.hiresTimer - t0; } catch (e1) {}
    return { ok: true, lane: r === true && state.nativeExtractMs >= 0 ? "native" : "jsx", path: payloadPath(i) };
  }

  function load(i) {
    /* Engine guard: the ExtendScript File/Folder APIs below throw
       ReferenceError in non-ExtendScript engines (e.g. Node test
       harnesses evaluating the bundle for interop checks). Degrade to
       ES3 mode instead of escaping - the bundle is fully functional in
       pure ES3 without ExternalObject. */
    try {
      return loadInner(i);
    } catch (e) {
      state.lastError = "ESPAK: load failed (engine lacks ExtendScript File/Folder APIs?): " + String(e);
      return { ok: false, mode: "es3", error: state.lastError, lib: null, path: "" };
    }
  }

  function loadInner(i) {
    var t0 = 0;
    try { $.hiresTimer; t0 = $.hiresTimer; } catch (e0) {}
    state.lastError = "";
    /* Timings describe THIS load attempt, not the most recent historical
       extraction. A shared idempotent loader survives bundle re-evaluation, so
       stale values would otherwise make skip loads look like re-extractions. */
    state.accelExtractMs = -1;
    state.nativeExtractMs = -1;
    state.payloadExtractMs = -1;
    state.loadMs = -1;
    var idx = resolvePayload(i);
    if (idx === -2) {
      /* Explicit accelerator target. This matters once an accelerator-only
         bundle has been merged into a shared runtime that also has payloads:
         the accelerator name is not a payload name and must not resolve
         through PAYLOADS. */
      if (!loadAccelLib()) return { ok: false, mode: "es3", error: state.lastError, lib: null, path: accelPath() };
      state.lib = state.accelLib;
      state.mode = "native";
      try { state.loadMs = $.hiresTimer - t0; } catch (e3) {}
      return { ok: true, mode: "native", lib: state.accelLib, path: accelPath() };
    }
    if (idx === -1) {
      state.lastError = "ESPAK: unknown payload " + String(i) + " (have " + PAYLOADS.length + ")";
      return { ok: false, mode: "es3", error: state.lastError, lib: null, path: "" };
    }
    if (PAYLOADS.length === 0) {
      /* accelerator-only bundle: the accel IS the loadable lib */
      if (!loadAccelLib()) return { ok: false, mode: "es3", error: state.lastError, lib: null, path: accelPath() };
      state.lib = state.accelLib;
      state.mode = "native";
      try { state.loadMs = $.hiresTimer - t0; } catch (e3) {}
      return { ok: true, mode: "native", lib: state.accelLib, path: accelPath() };
    }
    if (payloadKind(idx) === "file") {
      /* arbitrary bundled file: materialize via extract(), never ExternalObject */
      state.lastError = "ESPAK: payload " + PAYLOADS[idx].name + " is kind=file (not a loadable DLL); use extract()/payloadPath()";
      return { ok: false, mode: "es3", error: state.lastError, lib: null, path: payloadPath(idx) };
    }
    if (!isExtracted(idx)) {
      loadAccelLib(); /* best-effort: the payload falls back to the JSX lane if this fails */
      var r = extractPayload(idx);
      if (!r.ok) return { ok: false, mode: "es3", error: r.error, lib: null, path: payloadPath(idx) };
      state.extracted[idx] = true;
    }
    var fsPath = null;
    try { fsPath = new File(payloadPath(idx)).fsName; } catch (e2) { fsPath = payloadPath(idx); }
    var cached = cachedLib(payloadPath(idx));
    if (cached) {
      state.lib = cached;
      state.mode = "native";
      try { state.loadMs = $.hiresTimer - t0; } catch (e3) {}
      return { ok: true, mode: "native", lib: cached, path: payloadPath(idx), cached: true };
    }
    try {
      var lib = new ExternalObject("lib:" + fsPath);
      cacheLib(payloadPath(idx), lib);
      state.lib = lib;
      state.mode = "native";
      try { state.loadMs = $.hiresTimer - t0; } catch (e3) {}
      return { ok: true, mode: "native", lib: lib, path: payloadPath(idx), cached: false };
    } catch (e4) {
      state.lastError = "ESPAK: ExternalObject load failed: " + String(e4);
      try {
        var diag = ExternalObject.search("lib:" + fsPath);
        state.lastError += " | search: " + String(diag);
      } catch (e5) {}
      return { ok: false, mode: "es3", error: state.lastError, lib: null, path: payloadPath(idx) };
    }
  }

  function resolvePayload(i) {
    if (typeof i === "string" && hasAccel() && i === ACCEL_NAME) return -2;
    if (PAYLOADS.length === 0) return 0;
    if (typeof i === "string") {
      var k;
      for (k = 0; k < PAYLOADS.length; k++) {
        if (PAYLOADS[k].name === i) return k;
      }
      return -1;
    }
    var idx = typeof i === "number" ? i : 0;
    if (idx < 0 || idx >= PAYLOADS.length) return -1;
    return idx;
  }

  /* Payload kind: "dll" (default - loadable via ExternalObject) or "file"
     (arbitrary bundled file - extract()/payloadPath() only, never load()). */
  function payloadKind(i) {
    return PAYLOADS[i] && PAYLOADS[i].kind === "file" ? "file" : "dll";
  }

  function attach(opts, i) {
    opts = opts || {};
    var result = load(i);
    var impl = opts.es3 || {};
    if (result.ok && result.mode === "native" && typeof opts.buildNative === "function") {
      var nativeImpl = null;
      try { nativeImpl = opts.buildNative(result.lib); } catch (e) {
        state.lastError = "ESPAK: buildNative failed: " + String(e) + "; keeping the ES3 implementation";
        result = { ok: false, mode: "es3", error: state.lastError, lib: null, path: result.path };
      }
      if (nativeImpl) impl = nativeImpl;
    }
    state.mode = result.mode;
    if (typeof opts.onMode === "function") {
      try { opts.onMode(result.mode, result.lib, impl); } catch (e2) {}
    }
    return { ok: result.ok, mode: result.mode, lib: result.lib, impl: impl, path: result.path, error: state.lastError };
  }

  function payloadSummary() {
    var a = [], k;
    for (k = 0; k < PAYLOADS.length; k++) {
      a.push({ name: PAYLOADS[k].name, version: PAYLOADS[k].version, fileName: PAYLOADS[k].fileName, len: PAYLOADS[k].len, kind: payloadKind(k) });
    }
    return a;
  }

  publicConfig = {
    bundleName: BUNDLE_NAME,
    cacheDir: cacheDir(),
    chunkSize: CHUNK,
    accel: hasAccel() ? { name: ACCEL_NAME, version: ACCEL_VERSION, fileName: accelFileName(), len: ACCEL_LEN, dir: accelDir() } : null,
    payloads: payloadSummary()
  };

  return {
    version: ESPAK_VERSION,
    supportsAccelTargetName: true,
    config: publicConfig,
    mode: function () { return state.mode; },
    lastError: function () { return state.lastError; },
    accelReady: function () { return state.accelReady; },
    accelPath: accelPath,
    accelExtractMs: function () { return state.accelExtractMs; },
    nativeExtractMs: function () { return state.nativeExtractMs; },
    extractMs: function () { return state.payloadExtractMs; },
    loadMs: function () { return state.loadMs; },
    isExtracted: function (i) {
      var idx = resolvePayload(i);
      if (idx === -1) return false;
      return isExtracted(idx);
    },
    payloadPath: payloadPath,
    cacheDir: cacheDir,
    registerPayload: registerPayload,
    registerPayloadsFront: registerPayloadsFront,
    registerInto: registerInto,
    accelUpgrades: accelUpgrades,
    extract: function (i) {
      state.payloadExtractMs = -1;
      state.nativeExtractMs = -1;
      var idx = resolvePayload(i);
      if (idx === -1) return { ok: false, error: "ESPAK: unknown payload " + String(i) };
      if (isExtracted(idx)) return { ok: true, already: true, lane: "skip", path: payloadPath(idx) };
      loadAccelLib();
      return extractPayload(idx);
    },
    load: load,
    attach: attach
  };
}());

(function () {
  var g = null;
  try { if (typeof $ !== "undefined" && $.global) { g = $.global; } } catch (e1) {}
  if (!g) { try { g = (function () { return this; })(); } catch (e2) {} }
  if (!g) return;
  /* Idempotent install: if a loader runtime is already present on the global
     (an earlier bundle in this file installed it), register THIS bundle's
     payloads into that runtime and reuse it — never ship a second loader.
     Exception: this bundle carries a DIFFERENT embedded accel (a version
     upgrade) — then it replaces the runtime so its accel extraction + GC
     take over. The existing runtime remains the facade for merges; its
     registerPayloadsFront folds this bundle's payloads in so load(0)/load(name)
     resolve across every registered bundle. */
  if (g.ESPAK && typeof g.ESPAK.registerPayload === "function" && !ESPACK.accelUpgrades(g.ESPAK)) {
    if (ESPACK.registerInto(g.ESPAK)) return;
  }
  g.ESPAK = ESPACK;
}());
