/*
 * ESPACK __ESPAK_VERSION__ self-extracting ExternalObject bundle (generated by espack-build.mjs - do not edit).
 * Bundle: __BUNDLE_NAME__
 * Payloads (n): __PAYLOAD_SUMMARY__
 * Accelerator (1, shared across all espack bundles): __ACCEL_SUMMARY__
 * Cache dirs: payloads %LOCALAPPDATA%/<bundle name>, accelerator %LOCALAPPDATA%/espack (or __ACCEL_DIR__)
 * Runtime decode chunk: __CHUNK_SIZE__ base64 chars per pass (JSX lane; measured: linear atob, no engine wedge)
 */
var ESPACK = (function () {
  var PAYLOADS = __PAYLOADS__;
  var CHUNK = __CHUNK_SIZE__;
  var BUNDLE_NAME = "__BUNDLE_NAME__";
  var CACHE_DIR_OVERRIDE = "__CACHE_DIR__";
  var ACCEL_NAME = "__ACCEL_NAME__";
  var ACCEL_VERSION = "__ACCEL_VERSION__";
  var ACCEL_LEN = __ACCEL_LEN__;
  var ACCEL_B64 = "__ACCEL_B64__";
  var ACCEL_DIR_OVERRIDE = "__ACCEL_DIR__";
  var ESPAK_VERSION = "__ESPAK_VERSION__";

  var state = { mode: "es3", lib: null, lastError: "", extracted: {}, accelReady: false, accelLib: null, accelExtractMs: -1, nativeExtractMs: -1, payloadExtractMs: -1, loadMs: -1 };

__ESB64_RUNTIME__

  function pathJoin(a, b) {
    var s = String(a);
    if (s.charAt(s.length - 1) !== "/") s += "/";
    return s + String(b);
  }

  function defaultCacheDir(name) {
    var la = null;
    try { la = $.getenv("LOCALAPPDATA"); } catch (e1) {}
    if (la) return pathJoin(String(la).replace(/\\/g, "/"), name);
    try { return pathJoin(Folder.temp.fsName.replace(/\\/g, "/"), "espack/" + name); } catch (e2) {}
    return pathJoin("C:/Users/Public/espack", name);
  }

  function cacheDir() {
    if (CACHE_DIR_OVERRIDE) return String(CACHE_DIR_OVERRIDE).replace(/\\/g, "/");
    return defaultCacheDir(BUNDLE_NAME);
  }

  function accelDir() {
    if (ACCEL_DIR_OVERRIDE) return String(ACCEL_DIR_OVERRIDE).replace(/\\/g, "/");
    return defaultCacheDir("espack");
  }

  function payloadPath(i) { return pathJoin(cacheDir(), PAYLOADS[i].fileName); }
  function accelFileName() { return ACCEL_NAME + "_v" + ACCEL_VERSION + ".dll"; }
  function accelPath() { return pathJoin(accelDir(), accelFileName()); }
  function hasAccel() { return ACCEL_LEN > 0; }

  function ensureDir(fsPath) {
    var parts = String(fsPath).split("/");
    if (parts.length < 2) return new Folder(fsPath).exists;
    var cur = parts[0] + "/" + parts[1];
    var i, f;
    for (i = 2; i < parts.length; i++) {
      cur += "/" + parts[i];
      f = new Folder(cur);
      if (!f.exists && !f.create()) return false;
    }
    return true;
  }

  function isExtracted(i) {
    try {
      var f = new File(payloadPath(i));
      if (!f.exists) return false;
      return f.length === PAYLOADS[i].len;
    } catch (e) { return false; }
  }

  function isAccelExtracted() {
    try {
      var f = new File(accelPath());
      if (!f.exists) return false;
      return f.length === ACCEL_LEN;
    } catch (e) { return false; }
  }

  function gcOldVersions(dir, name, currentFile) {
    try {
      var folder = new Folder(dir);
      var matches = folder.getFiles(name + "_v*.dll");
      var i;
      for (i = 0; i < matches.length; i++) {
        if (String(matches[i].name) !== currentFile) {
          try { matches[i].remove(); } catch (ignore) {}
        }
      }
    } catch (ignore) {}
  }

  function gcPayloadOld(i) { gcOldVersions(cacheDir(), PAYLOADS[i].name, PAYLOADS[i].fileName); }
  function gcAccelOld() { gcOldVersions(accelDir(), ACCEL_NAME, accelFileName()); }

  /* JSX lane: chunked atob decode -> per-chunk BINARY writes -> length verify. */
  function jsxWriteExtracted(b64, len, path, gcDir, gcName, gcCurrent) {
    var out = [];
    var n = b64.length;
    var i = 0;
    while (i < n) {
      var end = i + CHUNK;
      if (end > n) end = n;
      out.push(__espakB64.atob(b64.substring(i, end)));
      i = end;
    }
    var f = new File(path);
    f.encoding = "BINARY";
    var wroteAll = true;
    try {
      if (!f.open("w")) {
        state.lastError = "ESPAK: cannot open \"" + path + "\" for writing; staying in ES3 mode";
        return false;
      }
      var j;
      for (j = 0; j < out.length; j++) {
        if (!f.write(out[j])) wroteAll = false;
      }
      f.close();
    } catch (e) {
      try { f.close(); } catch (e2) {}
      state.lastError = "ESPAK: extraction write failed: " + String(e);
      return false;
    }
    if (!wroteAll || f.length !== len) {
      state.lastError = "ESPAK: extracted file is " + f.length + " bytes, expected " + len + "; staying in ES3 mode";
      try { f.remove(); } catch (e3) {}
      return false;
    }
    gcOldVersions(gcDir, gcName, gcCurrent);
    return true;
  }

  function extractAccel() {
    state.accelExtractMs = -1;
    if (!hasAccel()) return false;
    if (isAccelExtracted()) return true;
    if (!ensureDir(accelDir())) {
      state.lastError = "ESPAK: cannot create accelerator dir \"" + accelDir() + "\"; payloads will use the JSX lane";
      return false;
    }
    var t0 = 0;
    try { $.hiresTimer; t0 = $.hiresTimer; } catch (e0) {}
    var ok = jsxWriteExtracted(ACCEL_B64, ACCEL_LEN, accelPath(), accelDir(), ACCEL_NAME, accelFileName());
    if (ok) {
      try { state.accelExtractMs = $.hiresTimer - t0; } catch (e1) {}
    }
    return ok;
  }

  function loadAccelLib() {
    if (!hasAccel()) return false;
    if (!extractAccel()) return false;
    var fsPath = null;
    try { fsPath = new File(accelPath()).fsName; } catch (e2) { fsPath = accelPath(); }
    var cached = cachedLib(accelPath());
    if (cached) {
      state.accelLib = cached;
      state.accelReady = true;
      return true;
    }
    try {
      var lib = new ExternalObject("lib:" + fsPath);
      cacheLib(accelPath(), lib);
      state.accelLib = lib;
      state.accelReady = true;
      return true;
    } catch (e3) {
      state.lastError = "ESPAK: accelerator load failed: " + String(e3) + "; payloads will use the JSX lane";
      return false;
    }
  }

  function libCache() {
    var g = null;
    try { if (typeof $ !== "undefined" && $.global) { g = $.global; } } catch (e1) {}
    if (!g) return null;
    if (!g.__ESPAK_LIBS__) g.__ESPAK_LIBS__ = {};
    return g.__ESPAK_LIBS__;
  }

  function cachedLib(path) {
    var c = libCache();
    return c ? (c[path] || null) : null;
  }

  function cacheLib(path, lib) {
    var c = libCache();
    if (c) c[path] = lib;
  }

  /* Native lane: the shared accelerator decodes the payload straight to
     disk (b64decodeToFile - NUL-safe, no string channel). Any error code,
     non-numeric result, or length mismatch falls back to the JSX lane. */
  function nativeExtractPayload(i) {
    state.nativeExtractMs = -1;
    if (!state.accelReady || !state.accelLib) return false;
    if (!ensureDir(cacheDir())) {
      state.lastError = "ESPAK: cannot create cache dir \"" + cacheDir() + "\"; staying in ES3 mode";
      return false;
    }
    var t0 = 0;
    try { $.hiresTimer; t0 = $.hiresTimer; } catch (e0) {}
    var n = null;
    try { n = state.accelLib.b64decodeToFile(PAYLOADS[i].b64, payloadPath(i)); } catch (e) {
      state.lastError = "ESPAK: native extraction failed (" + String(e) + "); falling back to the JSX lane";
      return false;
    }
    if (typeof n !== "number" || n !== PAYLOADS[i].len) {
      state.lastError = "ESPAK: native extraction returned " + n + " bytes, expected " + PAYLOADS[i].len + "; falling back to the JSX lane";
      try { new File(payloadPath(i)).remove(); } catch (e1) {}
      return false;
    }
    gcPayloadOld(i);
    try { state.nativeExtractMs = $.hiresTimer - t0; } catch (e2) {}
    return true;
  }

  function extractPayload(i) {
    state.payloadExtractMs = -1;
    var t0 = 0;
    try { $.hiresTimer; t0 = $.hiresTimer; } catch (e0) {}
    var r = nativeExtractPayload(i);
    if (!r) {
      /* the native failure reason stays in state.lastError (surfaced even
         when the JSX-lane fallback succeeds); clear it for the JSX attempt
         only when it was a hard cache-dir failure we are about to retry. */
      var nativeNote = state.lastError;
      if (!ensureDir(cacheDir())) {
        state.lastError = "ESPAK: cannot create cache dir \"" + cacheDir() + "\"; staying in ES3 mode";
        return { ok: false, error: state.lastError };
      }
      var wrote = jsxWriteExtracted(PAYLOADS[i].b64, PAYLOADS[i].len, payloadPath(i), cacheDir(), PAYLOADS[i].name, PAYLOADS[i].fileName);
      if (!wrote) return { ok: false, error: state.lastError };
      if (nativeNote) state.lastError = nativeNote + " (payload extracted via the JSX lane instead)";
    }
    try { state.payloadExtractMs = $.hiresTimer - t0; } catch (e1) {}
    return { ok: true, lane: r === true && state.nativeExtractMs >= 0 ? "native" : "jsx", path: payloadPath(i) };
  }

  function load(i) {
    var t0 = 0;
    try { $.hiresTimer; t0 = $.hiresTimer; } catch (e0) {}
    state.lastError = "";
    var idx = resolvePayload(i);
    if (idx === -1) {
      state.lastError = "ESPAK: unknown payload " + String(i) + " (have " + PAYLOADS.length + ")";
      return { ok: false, mode: "es3", error: state.lastError, lib: null, path: "" };
    }
    if (PAYLOADS.length === 0) {
      /* accelerator-only bundle: the accel IS the loadable lib */
      if (!loadAccelLib()) return { ok: false, mode: "es3", error: state.lastError, lib: null, path: accelPath() };
      state.lib = state.accelLib;
      state.mode = "native";
      try { state.loadMs = $.hiresTimer - t0; } catch (e3) {}
      return { ok: true, mode: "native", lib: state.accelLib, path: accelPath() };
    }
    if (!isExtracted(idx)) {
      loadAccelLib(); /* best-effort: the payload falls back to the JSX lane if this fails */
      var r = extractPayload(idx);
      if (!r.ok) return { ok: false, mode: "es3", error: r.error, lib: null, path: payloadPath(idx) };
      state.extracted[idx] = true;
    }
    var fsPath = null;
    try { fsPath = new File(payloadPath(idx)).fsName; } catch (e2) { fsPath = payloadPath(idx); }
    var cached = cachedLib(payloadPath(idx));
    if (cached) {
      state.lib = cached;
      state.mode = "native";
      try { state.loadMs = $.hiresTimer - t0; } catch (e3) {}
      return { ok: true, mode: "native", lib: cached, path: payloadPath(idx), cached: true };
    }
    try {
      var lib = new ExternalObject("lib:" + fsPath);
      cacheLib(payloadPath(idx), lib);
      state.lib = lib;
      state.mode = "native";
      try { state.loadMs = $.hiresTimer - t0; } catch (e3) {}
      return { ok: true, mode: "native", lib: lib, path: payloadPath(idx), cached: false };
    } catch (e4) {
      state.lastError = "ESPAK: ExternalObject load failed: " + String(e4);
      try {
        var diag = ExternalObject.search("lib:" + fsPath);
        state.lastError += " | search: " + String(diag);
      } catch (e5) {}
      return { ok: false, mode: "es3", error: state.lastError, lib: null, path: payloadPath(idx) };
    }
  }

  function resolvePayload(i) {
    if (PAYLOADS.length === 0) return 0;
    if (typeof i === "string") {
      var k;
      for (k = 0; k < PAYLOADS.length; k++) {
        if (PAYLOADS[k].name === i) return k;
      }
      return -1;
    }
    var idx = typeof i === "number" ? i : 0;
    if (idx < 0 || idx >= PAYLOADS.length) return -1;
    return idx;
  }

  function attach(opts, i) {
    opts = opts || {};
    var result = load(i);
    var impl = opts.es3 || {};
    if (result.ok && result.mode === "native" && typeof opts.buildNative === "function") {
      var nativeImpl = null;
      try { nativeImpl = opts.buildNative(result.lib); } catch (e) {
        state.lastError = "ESPAK: buildNative failed: " + String(e) + "; keeping the ES3 implementation";
        result = { ok: false, mode: "es3", error: state.lastError, lib: null, path: result.path };
      }
      if (nativeImpl) impl = nativeImpl;
    }
    state.mode = result.mode;
    if (typeof opts.onMode === "function") {
      try { opts.onMode(result.mode, result.lib, impl); } catch (e2) {}
    }
    return { ok: result.ok, mode: result.mode, lib: result.lib, impl: impl, path: result.path, error: state.lastError };
  }

  function payloadSummary() {
    var a = [], k;
    for (k = 0; k < PAYLOADS.length; k++) {
      a.push({ name: PAYLOADS[k].name, version: PAYLOADS[k].version, fileName: PAYLOADS[k].fileName, len: PAYLOADS[k].len });
    }
    return a;
  }

  return {
    version: ESPAK_VERSION,
    config: {
      bundleName: BUNDLE_NAME,
      cacheDir: cacheDir(),
      chunkSize: CHUNK,
      accel: hasAccel() ? { name: ACCEL_NAME, version: ACCEL_VERSION, fileName: accelFileName(), len: ACCEL_LEN, dir: accelDir() } : null,
      payloads: payloadSummary()
    },
    mode: function () { return state.mode; },
    lastError: function () { return state.lastError; },
    accelReady: function () { return state.accelReady; },
    accelPath: accelPath,
    accelExtractMs: function () { return state.accelExtractMs; },
    nativeExtractMs: function () { return state.nativeExtractMs; },
    extractMs: function () { return state.payloadExtractMs; },
    loadMs: function () { return state.loadMs; },
    isExtracted: function (i) {
      var idx = resolvePayload(i);
      if (idx === -1) return false;
      return isExtracted(idx);
    },
    payloadPath: payloadPath,
    cacheDir: cacheDir,
    extract: function (i) {
      var idx = resolvePayload(i);
      if (idx === -1) return { ok: false, error: "ESPAK: unknown payload " + String(i) };
      if (isExtracted(idx)) return { ok: true, already: true, path: payloadPath(idx) };
      loadAccelLib();
      return extractPayload(idx);
    },
    load: load,
    attach: attach
  };
}());

(function () {
  var g = null;
  try { if (typeof $ !== "undefined" && $.global) { g = $.global; } } catch (e1) {}
  if (!g) { try { g = (function () { return this; })(); } catch (e2) {} }
  if (g) { g.ESPAK = ESPACK; }
}());
